In [1]:
from bs4 import BeautifulSoup
import psycopg2 as pg2
import logging
import requests
import time

In [18]:
import pandas as pd

In [3]:
page_recq = requests.get('http://tieba.baidu.com/f/index/forumclass', timeout=5)

In [4]:
soup = BeautifulSoup(page_recq.content, "html.parser")

In [22]:
r0 = soup.find_all('ul',{'class':'item-list-ul clearfix'})

In [21]:
tieba = pd.DataFrame(columns=['name','url'])

In [15]:
print r.find('a',{'rel':'noopener'}).getText()

港台东南亚明星

In [ ]:
tieba = pd.DataFrame(columns=['name','url'])

In [49]:
tieba.to_csv('tieba.csv', encoding='utf-8')

In [37]:
t=[]
for x in r0:
    y0 = x.find_all('a',{'rel':'noopener'})
    for y in y0:
        t.append([y.getText(),y['href']])

In [51]:
tieba.head()

      name                                                url
0  港台东南亚明星  /f/index/forumpark?cn=%E6%B8%AF%E5%8F%B0%E4%B8...
1     内地明星  /f/index/forumpark?cn=%E5%86%85%E5%9C%B0%E6%98...
2     韩国明星  /f/index/forumpark?cn=%E9%9F%A9%E5%9B%BD%E6%98...
3     日本明星  /f/index/forumpark?cn=%E6%97%A5%E6%9C%AC%E6%98...
4     时尚人物  /f/index/forumpark?cn=%E6%97%B6%E5%B0%9A%E4%BA...

In [65]:
tieba.shape

(454, 2)

In [67]:
tieba.tail()

        name                                                url
449   其他类型企业  /f/index/forumpark?cn=%E5%85%B6%E4%BB%96%E7%B1...
450   食品饮料企业  /f/index/forumpark?cn=%E9%A3%9F%E5%93%81%E9%A5...
451   贴吧管理中心  /f/index/forumpark?cn=%E8%B4%B4%E5%90%A7%E7%AE...
452  贴吧活动与交流  /f/index/forumpark?cn=%E8%B4%B4%E5%90%A7%E6%B4...
453   百度其他产品  /f/index/forumpark?cn=%E7%99%BE%E5%BA%A6%E5%85...

In [68]:
page = 0
for i in range(454):
    page_recq = requests.get('http://tieba.baidu.com' + tieba.url[i], timeout=60)
    page = page + 1
    print page
    soup = BeautifulSoup(page_recq.content, "html.parser")
    bar0 = soup.find_all('div',{'class':'ba_content'})
    for b in bar0:
        name = b.find('p',{'class':'ba_name'}).getText()
        members = b.find('span',{'class':'ba_m_num'}).getText()
        posts = b.find('span',{'class':'ba_p_num'}).getText()
        des = b.find('p',{'class':'ba_desc'}).getText()
        conn = pg2.connect(host="localhost",database="postgres", user="postgres", password="postgres",connect_timeout=10)
        cur = conn.cursor()
        sql = """INSERT INTO t0(name, members, posts, description) VALUES(%s, %s, %s, %s);"""
        cur.execute(sql, (name, members, posts, des))
        conn.commit()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454

In [55]:
soup = BeautifulSoup(page_recq.content, "html.parser")

In [58]:
bar0 = soup.find('div',{'class':'ba_content'})

In [60]:
print bar0

<div class="ba_content"><p class="ba_name">周杰伦吧</p><p class="ba_num clearfix"><span class="ba_m_num">2773993</span><span class="ba_p_num">81770651</span></p><p class="ba_desc">全球最大的周杰伦粉丝聚集地</p></div>

In [61]:
b=bar0

In [62]:
name = b.find('p',{'class':'ba_name'}).getText()
members = b.find('span',{'class':'ba_m_num'}).getText()
posts = b.find('span',{'class':'ba_p_num'}).getText()
des = b.find('p',{'class':'ba_desc'}).getText()

In [63]:
print name, members, posts, des

周杰伦吧 2773993 81770651 全球最大的周杰伦粉丝聚集地

In [64]:
conn = pg2.connect(host="localhost",database="postgres", user="postgres", password="postgres",connect_timeout=10)
cur = conn.cursor()
sql = """INSERT INTO t(name, members, posts, description) VALUES(%s, %s, %s, %s);"""
cur.execute(sql, (name, members, posts, des))
conn.commit()